version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - '4566-4583:4566-4583'
    env_file:
      - resource-service/.env.local
    volumes:
      - ${TEMPDIR:-/tmp/localstack}:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  resource-service-db:
    image: postgres:12
    container_name: resource-service-db
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 100s
      timeout: 5s
      retries: 5
    volumes:
      - resource-service-db-data:/var/lib/postgresql/data
    env_file:
      - resource-service/.env.local

  song-service-db:
    image: postgres:12
    container_name: song-service-db
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 100s
      timeout: 5s
      retries: 5
    volumes:
      - song-service-db-data:/var/lib/postgresql/data
    env_file:
      - song-service/.env.local
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  resource-service:
    container_name: resource-service-app
    build: resource-service
    ports:
      - "8081:8081"
    depends_on:
      resource-service-db:
        condition: service_healthy
    env_file:
      - resource-service/.env.local
  song-service:
    container_name: song-service-app
    build: song-service
    ports:
      - "8082:8082"
    depends_on:
      song-service-db:
        condition: service_healthy
    env_file:
      - song-service/.env.local
  resource-processor:
    container_name: resource-processor-app
    build: resource-processor
    ports:
      - "8083:8083"
    env_file:
      - resource-processor/.env.local
    depends_on:
      rabbitmq:
        condition: service_healthy
volumes:
  resource-service-db-data:
    driver: local
  song-service-db-data:
    driver: local
