version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - '4566-4583:4566-4583'
    env_file:
      - resource-service/.env.local
    volumes:
      - ${TEMPDIR:-/tmp/localstack}:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  # Resource-Service containers
  resource-service-db:
    image: postgres:12
    ports:
      - "5433:5432"
    volumes:
      - resource-service-db-data:/var/lib/postgresql/data
    env_file:
      - ./resource-service/.env.local

volumes:
  resource-service-db-data:
    driver: local