server:
  port: 8083
  error:
    whitelabel:
      enabled: false
spring:
  application:
    name: resource-processor
  aop:
    proxy-target-class: false
  main:
    allow-bean-definition-overriding: true
  web:
    locale: en
    resources:
      add-mappings: false
  profiles:
    active: ${SPRING_ACTIVE_PROFILES:dev}
  jmx:
    enabled: false
  mvc:
    throw-exception-if-no-handler-found: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  output:
    ansi:
      enabled: detect
  rabbitmq:
    host: ${RABBIT_DOCKER_HOST:RABBIT_LOCAL_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    queue-name: ${RABBIT_RESOURCE_CREATED_QUEUE_NAME}
    exchange-name: ${RABBIT_RESOURCE_CREATED_EXCHANGE_NAME}
    dead-letter-queue-name: ${RABBIT_RESOURCE_CREATED_DEAD_LETTER_QUEUE_NAME}
    dead-letter-queue-ttl: ${RABBIT_RESOURCE_CREATED_DEAD_LETTER_QUEUE_TTL}
    dead-letter-exchange-name: ${RABBIT_RESOURCE_CREATED_DEAD_LETTER_EXCHANGE_NAME}
    dead-letter-max-deaths-count: ${RABBIT_RESOURCE_CREATED_DEAD_LETTER_MAX_DEATHS_COUNT}
    parking-lot-queue-name: ${RABBIT_RESOURCE_CREATED_PARKING_LOT_QUEUE_NAME}
    parking-lot-exchange-name: ${RABBIT_RESOURCE_CREATED_PARKING_LOT_EXCHANGE_NAME}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: ${RABBIT_LISTENER_INITIAL_INTERVAL}
          max-attempts: ${RABBIT_LISTENER_MAX_ATTEMPTS}
          max-interval: ${RABBIT_LISTENER_MAX_INTERVAL}
          multiplier: ${RABBIT_LISTENER_MULTIPLIER}
configuration:
  resource-service:
    url: ${RESOURCE_DOCKER_SERVICE_URL:RESOURCE_LOCAL_SERVICE_URL}
    request:
      retries-count: ${RESOURCE_SERVICE_RETRIES_COUNT}
      base-retry-delay: ${RESOURCE_SERVICE_BASE_RETRY_DELAY}
      max-retry-delay: ${RESOURCE_SERVICE_MAX_RETRY_DELAY}
      retry-delay-multiplier: ${RESOURCE_SERVICE_RETRY_DELAY_MULTIPLIER}
  song-service:
    url: ${SONG_DOCKER_SERVICE_URL:SONG_LOCAL_SERVICE_URL}
    request:
      retries-count: ${SONG_SERVICE_RETRIES_COUNT}
      base-retry-delay: ${SONG_SERVICE_BASE_RETRY_DELAY}
      max-retry-delay: ${SONG_SERVICE_MAX_RETRY_DELAY}
      retry-delay-multiplier: ${SONG_SERVICE_RETRY_DELAY_MULTIPLIER}
